name: (Authentication) Create & push docker environment for test

on:
  pull_request:
    paths: 
       - 'Microservices/**'
    branches: [ "development" ]
    types: [closed] 

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest

    env:
      TAG: pr-${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_HUB_REPO_AUTH }}:latest
            ${{ secrets.DOCKER_HUB_USER }}/${{ secrets.DOCKER_HUB_REPO_AUTH }}:${{ env.TAG }}